export enum Screens {
    WELCOME = "index",
    INSERT_PHONE_NUMBER = "(auth)/insert-phone-number",
    VALIDATE_OTP_CODE = "(auth)/validate-otp-code",
    CREATE_USER_PROFILE = "(settings)/(user)/CreateProfile",
    SETTINGS = "(settings)/Settings",
    PRIVATE_CHAT_SCREEN = 'PrivateChatScreen',
    GROUPS_CHAT_SCREEN = 'GroupsChatScreen',
    PRIVATE_CHAT = 'PrivateChat',
    GROUP_CHAT = 'GroupChat',
    STATUS = 'Status',
    CALLS = 'Calls',
    USER_PROFILE = 'UserProfile',
    CHAT = '(chat)',
}